import os
import joblib
import streamlit as st

# ===================================================
# Page Configuration
# ===================================================

st.set_page_config(
    page_title="Fake News Detection System",
    page_icon="📰",
    layout="centered"
)

# ===================================================
# Sidebar
# ===================================================

st.sidebar.title("📰 Fake News Detector")

st.sidebar.markdown("### 🤖 Model")
st.sidebar.success("Logistic Regression")

st.sidebar.markdown("### 📊 Dataset")
st.sidebar.info("44,898 News Articles")

st.sidebar.markdown("### 🎯 Accuracy")
st.sidebar.success("98.94%")

st.sidebar.markdown("### ⚙️ Features")

st.sidebar.markdown("""
- ✅ TF-IDF Vectorization
- ✅ Real-time Prediction
- ✅ Confidence Score
- ✅ Probability Analysis
""")

st.sidebar.markdown("---")

st.sidebar.caption("Developed by **Bhavya Posham**")

# ===================================================
# Load Model
# ===================================================

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

model = joblib.load(
    os.path.join(BASE_DIR, "models", "logistic_regression.pkl")
)

vectorizer = joblib.load(
    os.path.join(BASE_DIR, "models", "tfidf_vectorizer.pkl")
)

# ===================================================
# Title
# ===================================================

st.title("📰 Fake News Detection System")

st.caption("Developed by **Bhavya Posham**")

st.markdown("""
Detect whether a news article is **Real** or **Fake** using a Machine Learning model trained on nearly **45,000 news articles**.

Paste an article below and click **Predict**.
""")

st.divider()

# ===================================================
# Input
# ===================================================

news = st.text_area(
    "Paste News Article",
    height=250,
    placeholder="Paste the complete news article here..."
)

if news:

    col1, col2 = st.columns(2)

    with col1:
        st.metric("📝 Words", len(news.split()))

    with col2:
        st.metric("🔤 Characters", len(news))

# ===================================================
# Prediction
# ===================================================

predict = st.button(
    "🔍 Predict",
    use_container_width=True
)

if predict:

    if news.strip() == "":
        st.warning("⚠️ Please paste a news article first.")

    else:

        with st.spinner("Analyzing article..."):

            news_vector = vectorizer.transform([news])

            prediction = model.predict(news_vector)[0]

            probability = model.predict_proba(news_vector)[0]

            fake_prob = probability[0]
            real_prob = probability[1]

            confidence = max(fake_prob, real_prob)

        st.divider()

        # Prediction Result

        if prediction == 1:
            st.success("✅ This appears to be **REAL NEWS**.")
        else:
            st.error("❌ This appears to be **FAKE NEWS**.")

        # Confidence

        st.subheader("🎯 Prediction Confidence")

        st.progress(confidence)

        st.metric(
            "Confidence Score",
            f"{confidence*100:.2f}%"
        )

        # Probabilities

        st.subheader("📊 Prediction Probabilities")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "🟥 Fake News",
                f"{fake_prob*100:.2f}%"
            )

        with col2:
            st.metric(
                "🟩 Real News",
                f"{real_prob*100:.2f}%"
            )

# ===================================================
# About Model
# ===================================================

with st.expander("ℹ️ About this Model"):

    st.markdown("""
## 🧠 Model Information

**Algorithm**
- Logistic Regression

**Feature Extraction**
- TF-IDF Vectorization

**Dataset**
- ISOT Fake News Dataset
- 44,898 News Articles

**Performance**
- Accuracy: **98.94%**

---

## ⚙️ Prediction Pipeline

News Article

⬇️

Text Cleaning & TF-IDF Vectorization

⬇️

Logistic Regression Classifier

⬇️

Real / Fake Prediction

⬇️

Confidence Score

---

## 💻 Tech Stack

- Python
- Scikit-learn
- Streamlit
- Pandas
- Joblib
""")

# ===================================================
# Disclaimer
# ===================================================

st.warning(
    "⚠️ This application is intended for educational purposes only. "
    "Predictions are generated by a machine learning model and should not be considered definitive verification of news authenticity."
)

# ===================================================
# Footer
# ===================================================

st.divider()

st.caption(
    """
Built with ❤️ using

**Python • Streamlit • Scikit-learn • TF-IDF • Logistic Regression**
"""
)
